### ISSUE TITLE
Support PHP 8.1

### ISSUE THREAD

**Issue by linawolf** [martin-helmich/typo3-typoscript-lint#129]
As TYPO3 12.0 dropped support for PHP 8.0

**Comment by oliverklee** [comment]
PHP 8.1 already is supported as `^8.0` includes 8.1, 8.2 etc.: https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by martin-helmich** [comment]
As mentioned in https://github.com/martin-helmich/typo3-typoscript-lint/issues/129#issuecomment-1249245893, PHP 8.1 is supported, and this project is regularly tested against 8.1 since https://github.com/martin-helmich/typo3-typoscript-lint/pull/123. If I'm not mistaken, no further action should be required on this one.
